extends: default

rules:
  # Increase line length limit for complex YAML files
  line-length:
    max: 120
    level: warning

  # Allow long lines in comments  
  comments:
    min-spaces-from-content: 1

  # Be more lenient with indentation
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Allow empty documents (useful for conditional includes)
  document-start: disable
  document-end: disable

  # Allow trailing spaces in comments
  trailing-spaces:
    level: warning

  # Allow empty lines at end of file
  empty-lines:
    max-end: 2

  # Be more flexible with truthy values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: true

ignore: |
  **/node_modules/
  **/.git/
  **/vendor/
  **/*.min.yml
  **/*.min.yaml