# Yamllint configuration - Focused on real issues only
---
extends: default

rules:
  # Allow longer lines to reduce noise
  line-length:
    max: 120  # Increased from 80 to reduce false positives
    level: warning
  
  # Be less strict about indentation in some cases
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  
  # Don't require document start for compose files
  document-start:
    present: false
  
  # Allow some formatting flexibility
  comments:
    min-spaces-from-content: 1
  
  # Don't be too strict about empty lines
  empty-lines:
    max: 2
    max-start: 1
    max-end: 1
  
  # Allow trailing spaces in some contexts
  trailing-spaces:
    level: warning