// <auto-generated />
using System;
using MeAjudaAi.Modules.Locations.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeAjudaAi.Modules.Locations.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LocationsDbContext))]
    [Migration("20251212002108_InitialAllowedCities")]
    partial class InitialAllowedCities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("locations")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeAjudaAi.Modules.Locations.Domain.Entities.AllowedCity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("IbgeCode")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("StateSigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .IsFixedLength();

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("IbgeCode")
                        .IsUnique()
                        .HasDatabaseName("IX_AllowedCities_IbgeCode")
                        .HasFilter("\"IbgeCode\" IS NOT NULL");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_AllowedCities_IsActive");

                    b.HasIndex("CityName", "StateSigla")
                        .IsUnique()
                        .HasDatabaseName("IX_AllowedCities_CityName_State");

                    b.ToTable("allowed_cities", "locations");
                });
#pragma warning restore 612, 618
        }
    }
}
