CREATE SCHEMA IF NOT EXISTS identity;

GRANT ALL ON SCHEMA identity TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA identity GRANT ALL ON TABLES TO CURRENT_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA identity GRANT ALL ON SEQUENCES TO CURRENT_USER;
