# Yamllint configuration - Focused on real issues only
---
extends: default

rules:
  # Allow longer lines with smart exemptions
  line-length:
    max: 120  # Increased from 80 to reduce false positives
    level: warning
    allow-non-breakable-words: true       # Allow long URLs
    allow-non-breakable-inline-mappings: true  # Allow long inline mappings
  
  # Be less strict about indentation in some cases
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  
  # Require document start for clarity (compose files can override)
  document-start:
    present: true
  
  # Allow some formatting flexibility
  comments:
    min-spaces-from-content: 1
  
  # Don't be too strict about empty lines
  empty-lines:
    max: 2
    max-start: 1
    max-end: 1
  
  # Enforce clean whitespace - trailing spaces cause diff churn
  trailing-spaces:
    level: error