// <auto-generated />
using System;
using MeAjudaAi.Modules.Bookings.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeAjudaAi.Modules.Bookings.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BookingsDbContext))]
    [Migration("20260421163938_Fix_Indices_And_Timestamps")]
    partial class Fix_Indices_And_Timestamps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bookings")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeAjudaAi.Modules.Bookings.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Status");

                    b.HasIndex("ProviderId", "Status");

                    b.ToTable("bookings", "bookings");
                });

            modelBuilder.Entity("MeAjudaAi.Modules.Bookings.Domain.Entities.ProviderSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId")
                        .IsUnique();

                    b.ToTable("provider_schedules", "bookings");
                });

            modelBuilder.Entity("MeAjudaAi.Modules.Bookings.Domain.Entities.Booking", b =>
                {
                    b.OwnsOne("MeAjudaAi.Modules.Bookings.Domain.ValueObjects.TimeSlot", "TimeSlot", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("End")
                                .HasColumnType("timestamptz")
                                .HasColumnName("end_time");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("timestamptz")
                                .HasColumnName("start_time");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings", "bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.Navigation("TimeSlot")
                        .IsRequired();
                });

            modelBuilder.Entity("MeAjudaAi.Modules.Bookings.Domain.Entities.ProviderSchedule", b =>
                {
                    b.OwnsMany("MeAjudaAi.Modules.Bookings.Domain.ValueObjects.Availability", "Availabilities", b1 =>
                        {
                            b1.Property<Guid>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("DayOfWeek")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("day_of_week");

                            b1.Property<Guid>("provider_schedule_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("provider_schedule_id");

                            b1.HasIndex("DayOfWeek", "provider_schedule_id")
                                .IsUnique();

                            b1.ToTable("provider_availabilities", "bookings");

                            b1.WithOwner()
                                .HasForeignKey("provider_schedule_id");

                            b1.OwnsMany("MeAjudaAi.Modules.Bookings.Domain.ValueObjects.TimeSlot", "Slots", b2 =>
                                {
                                    b2.Property<Guid>("id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("End")
                                        .HasColumnType("timestamptz")
                                        .HasColumnName("end_time");

                                    b2.Property<DateTime>("Start")
                                        .HasColumnType("timestamptz")
                                        .HasColumnName("start_time");

                                    b2.Property<Guid>("availability_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("id");

                                    b2.HasIndex("availability_id");

                                    b2.ToTable("provider_availability_slots", "bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("availability_id");
                                });

                            b1.Navigation("Slots");
                        });

                    b.Navigation("Availabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
